<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Cogfather.Contracts\Cogfather.Contracts.csproj" />
      <ProjectReference Include="..\Cogfather.HQ.Domain\Cogfather.HQ.Domain.csproj" />
    </ItemGroup>

</Project>
