stages:
  - build
  - test
  - quality

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "true"
  DOTNET_CLI_TELEMETRY_OPTOUT: "true"
  DOTNET_NOLOGO: "true"

default:
  image: mcr.microsoft.com/dotnet/sdk:10.0

format:
  stage: build
  script:
    - cd Cogfather
    - dotnet restore
    - dotnet format --verify-no-changes

build:
  stage: build
  script:
    - cd Cogfather
    - dotnet restore
    - dotnet build --no-restore --configuration Release

test:
  stage: test
  script:
    - cd Cogfather
    - dotnet restore
    - dotnet test --configuration Release --no-restore --logger "junit;LogFilePath=../../TestResults/junit-{assembly}.xml" --collect:"XPlat Code Coverage" --results-directory ../../TestResults/
  artifacts:
    when: always
    reports:
      junit: TestResults/junit-*.xml
      coverage_report:
        coverage_format: cobertura
        path: TestResults/**/coverage.cobertura.xml
    expire_in: 1 week
  coverage: '/\|\s*Total\s*\|[^|]*\|[^|]*\|\s*([\d.]+)%/'

sonarqube:
  stage: quality
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "sonar-scanner-${CI_COMMIT_REF_SLUG}"
    paths:
      - .sonar/cache
  script:
    - apt-get update -qq && apt-get install -y -qq default-jre-headless
    - dotnet tool install --global dotnet-sonarscanner
    - dotnet tool install --global dotnet-coverage
    - export PATH="$PATH:$HOME/.dotnet/tools"
    - cd Cogfather
    - dotnet restore
    - dotnet-sonarscanner begin /k:"bsr2526-pro-zad-har-92678-92690-92699" /n:"Cogfather" /d:sonar.host.url="https://sonarqube.oroshi.app" /d:sonar.token="$SONAR_TOKEN" /d:sonar.cs.vscoveragexml.reportsPaths="coverage.xml"
    - dotnet build --no-restore
    - dotnet-coverage collect "dotnet test --no-build" -f xml -o coverage.xml
    - dotnet-sonarscanner end /d:sonar.token="$SONAR_TOKEN"
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
